---
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
